//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPerLa.Web.LaPerLaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="District", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class District : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((this.DistrictIdField.Equals(value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PositionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((this.DistrictIdField.Equals(value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PositionId {
            get {
                return this.PositionIdField;
            }
            set {
                if ((this.PositionIdField.Equals(value) != true)) {
                    this.PositionIdField = value;
                    this.RaisePropertyChanged("PositionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName {
            get {
                return this.PositionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionNameField, value) != true)) {
                    this.PositionNameField = value;
                    this.RaisePropertyChanged("PositionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChineseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PositionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChineseName {
            get {
                return this.ChineseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChineseNameField, value) != true)) {
                    this.ChineseNameField = value;
                    this.RaisePropertyChanged("ChineseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishName {
            get {
                return this.EnglishNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishNameField, value) != true)) {
                    this.EnglishNameField = value;
                    this.RaisePropertyChanged("EnglishName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PositionId {
            get {
                return this.PositionIdField;
            }
            set {
                if ((this.PositionIdField.Equals(value) != true)) {
                    this.PositionIdField = value;
                    this.RaisePropertyChanged("PositionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeSale", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class EmployeeSale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActualSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeSaleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TargetSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ActualSale {
            get {
                return this.ActualSaleField;
            }
            set {
                if ((this.ActualSaleField.Equals(value) != true)) {
                    this.ActualSaleField = value;
                    this.RaisePropertyChanged("ActualSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Days {
            get {
                return this.DaysField;
            }
            set {
                if ((this.DaysField.Equals(value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeSaleId {
            get {
                return this.EmployeeSaleIdField;
            }
            set {
                if ((this.EmployeeSaleIdField.Equals(value) != true)) {
                    this.EmployeeSaleIdField = value;
                    this.RaisePropertyChanged("EmployeeSaleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Month {
            get {
                return this.MonthField;
            }
            set {
                if ((object.ReferenceEquals(this.MonthField, value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Sale {
            get {
                return this.SaleField;
            }
            set {
                if ((this.SaleField.Equals(value) != true)) {
                    this.SaleField = value;
                    this.RaisePropertyChanged("Sale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TargetSale {
            get {
                return this.TargetSaleField;
            }
            set {
                if ((this.TargetSaleField.Equals(value) != true)) {
                    this.TargetSaleField = value;
                    this.RaisePropertyChanged("TargetSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Week {
            get {
                return this.WeekField;
            }
            set {
                if ((this.WeekField.Equals(value) != true)) {
                    this.WeekField = value;
                    this.RaisePropertyChanged("Week");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeTypeSale", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class EmployeeTypeSale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeTypeSaleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Actual {
            get {
                return this.ActualField;
            }
            set {
                if ((this.ActualField.Equals(value) != true)) {
                    this.ActualField = value;
                    this.RaisePropertyChanged("Actual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeTypeSaleId {
            get {
                return this.EmployeeTypeSaleIdField;
            }
            set {
                if ((this.EmployeeTypeSaleIdField.Equals(value) != true)) {
                    this.EmployeeTypeSaleIdField = value;
                    this.RaisePropertyChanged("EmployeeTypeSaleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Month {
            get {
                return this.MonthField;
            }
            set {
                if ((object.ReferenceEquals(this.MonthField, value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleType {
            get {
                return this.SaleTypeField;
            }
            set {
                if ((this.SaleTypeField.Equals(value) != true)) {
                    this.SaleTypeField = value;
                    this.RaisePropertyChanged("SaleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Target {
            get {
                return this.TargetField;
            }
            set {
                if ((this.TargetField.Equals(value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class Shop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShopNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShopTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((this.DistrictIdField.Equals(value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShopName {
            get {
                return this.ShopNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopNameField, value) != true)) {
                    this.ShopNameField = value;
                    this.RaisePropertyChanged("ShopName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopType {
            get {
                return this.ShopTypeField;
            }
            set {
                if ((this.ShopTypeField.Equals(value) != true)) {
                    this.ShopTypeField = value;
                    this.RaisePropertyChanged("ShopType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bonus", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class Bonus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CityPoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, System.Collections.Generic.Dictionary<long, System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Rule>>> EmployeeRuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, LaPerLa.Web.LaPerLaService.ShopSale> ShopSaleListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CityPool {
            get {
                return this.CityPoolField;
            }
            set {
                if ((this.CityPoolField.Equals(value) != true)) {
                    this.CityPoolField = value;
                    this.RaisePropertyChanged("CityPool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((this.DistrictIdField.Equals(value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, System.Collections.Generic.Dictionary<long, System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Rule>>> EmployeeRule {
            get {
                return this.EmployeeRuleField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeRuleField, value) != true)) {
                    this.EmployeeRuleField = value;
                    this.RaisePropertyChanged("EmployeeRule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, LaPerLa.Web.LaPerLaService.ShopSale> ShopSaleList {
            get {
                return this.ShopSaleListField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopSaleListField, value) != true)) {
                    this.ShopSaleListField = value;
                    this.RaisePropertyChanged("ShopSaleList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rule", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class Rule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OperationMaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OperationMinValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OperationValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PositionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RuleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RuleOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RuleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((this.BonusField.Equals(value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OperationMaxValue {
            get {
                return this.OperationMaxValueField;
            }
            set {
                if ((this.OperationMaxValueField.Equals(value) != true)) {
                    this.OperationMaxValueField = value;
                    this.RaisePropertyChanged("OperationMaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OperationMinValue {
            get {
                return this.OperationMinValueField;
            }
            set {
                if ((this.OperationMinValueField.Equals(value) != true)) {
                    this.OperationMinValueField = value;
                    this.RaisePropertyChanged("OperationMinValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationType {
            get {
                return this.OperationTypeField;
            }
            set {
                if ((this.OperationTypeField.Equals(value) != true)) {
                    this.OperationTypeField = value;
                    this.RaisePropertyChanged("OperationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OperationValue {
            get {
                return this.OperationValueField;
            }
            set {
                if ((this.OperationValueField.Equals(value) != true)) {
                    this.OperationValueField = value;
                    this.RaisePropertyChanged("OperationValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PositionId {
            get {
                return this.PositionIdField;
            }
            set {
                if ((this.PositionIdField.Equals(value) != true)) {
                    this.PositionIdField = value;
                    this.RaisePropertyChanged("PositionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleDescription {
            get {
                return this.RuleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleDescriptionField, value) != true)) {
                    this.RuleDescriptionField = value;
                    this.RaisePropertyChanged("RuleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RuleId {
            get {
                return this.RuleIdField;
            }
            set {
                if ((this.RuleIdField.Equals(value) != true)) {
                    this.RuleIdField = value;
                    this.RaisePropertyChanged("RuleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RuleOrder {
            get {
                return this.RuleOrderField;
            }
            set {
                if ((this.RuleOrderField.Equals(value) != true)) {
                    this.RuleOrderField = value;
                    this.RaisePropertyChanged("RuleOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RuleType {
            get {
                return this.RuleTypeField;
            }
            set {
                if ((this.RuleTypeField.Equals(value) != true)) {
                    this.RuleTypeField = value;
                    this.RaisePropertyChanged("RuleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopSale", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class ShopSale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActualSalesWithTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActualSalesWithoutTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ActualWeekSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ShopPoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShopSaleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TargetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TargetWeekSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ActualSalesWithTax {
            get {
                return this.ActualSalesWithTaxField;
            }
            set {
                if ((this.ActualSalesWithTaxField.Equals(value) != true)) {
                    this.ActualSalesWithTaxField = value;
                    this.RaisePropertyChanged("ActualSalesWithTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ActualSalesWithoutTax {
            get {
                return this.ActualSalesWithoutTaxField;
            }
            set {
                if ((this.ActualSalesWithoutTaxField.Equals(value) != true)) {
                    this.ActualSalesWithoutTaxField = value;
                    this.RaisePropertyChanged("ActualSalesWithoutTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ActualWeekSale {
            get {
                return this.ActualWeekSaleField;
            }
            set {
                if ((this.ActualWeekSaleField.Equals(value) != true)) {
                    this.ActualWeekSaleField = value;
                    this.RaisePropertyChanged("ActualWeekSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((this.DistrictIdField.Equals(value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Month {
            get {
                return this.MonthField;
            }
            set {
                if ((object.ReferenceEquals(this.MonthField, value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ShopPool {
            get {
                return this.ShopPoolField;
            }
            set {
                if ((this.ShopPoolField.Equals(value) != true)) {
                    this.ShopPoolField = value;
                    this.RaisePropertyChanged("ShopPool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShopSaleId {
            get {
                return this.ShopSaleIdField;
            }
            set {
                if ((this.ShopSaleIdField.Equals(value) != true)) {
                    this.ShopSaleIdField = value;
                    this.RaisePropertyChanged("ShopSaleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Target {
            get {
                return this.TargetField;
            }
            set {
                if ((this.TargetField.Equals(value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TargetWeekSale {
            get {
                return this.TargetWeekSaleField;
            }
            set {
                if ((this.TargetWeekSaleField.Equals(value) != true)) {
                    this.TargetWeekSaleField = value;
                    this.RaisePropertyChanged("TargetWeekSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((this.TaxField.Equals(value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Week {
            get {
                return this.WeekField;
            }
            set {
                if ((this.WeekField.Equals(value) != true)) {
                    this.WeekField = value;
                    this.RaisePropertyChanged("Week");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/LaPerLa.BusinessModel")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLoginTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLoginTime {
            get {
                return this.LastLoginTimeField;
            }
            set {
                if ((this.LastLoginTimeField.Equals(value) != true)) {
                    this.LastLoginTimeField = value;
                    this.RaisePropertyChanged("LastLoginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LaPerLaService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrict/AddDisctrict", ReplyAction="http://tempuri.org/IDistrict/AddDisctrictResponse")]
        LaPerLa.Web.LaPerLaService.District AddDisctrict(LaPerLa.Web.LaPerLaService.District info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrict/AddDisctrict", ReplyAction="http://tempuri.org/IDistrict/AddDisctrictResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.District> AddDisctrictAsync(LaPerLa.Web.LaPerLaService.District info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrict/QueryAllDistricts", ReplyAction="http://tempuri.org/IDistrict/QueryAllDistrictsResponse")]
        System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.District> QueryAllDistricts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrict/QueryAllDistricts", ReplyAction="http://tempuri.org/IDistrict/QueryAllDistrictsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.District>> QueryAllDistrictsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrict/GetDistrictById", ReplyAction="http://tempuri.org/IDistrict/GetDistrictByIdResponse")]
        LaPerLa.Web.LaPerLaService.District GetDistrictById(long districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrict/GetDistrictById", ReplyAction="http://tempuri.org/IDistrict/GetDistrictByIdResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.District> GetDistrictByIdAsync(long districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosition/AddPosition", ReplyAction="http://tempuri.org/IPosition/AddPositionResponse")]
        LaPerLa.Web.LaPerLaService.Position AddPosition(LaPerLa.Web.LaPerLaService.Position info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosition/AddPosition", ReplyAction="http://tempuri.org/IPosition/AddPositionResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Position> AddPositionAsync(LaPerLa.Web.LaPerLaService.Position info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosition/GetPositionByIds", ReplyAction="http://tempuri.org/IPosition/GetPositionByIdsResponse")]
        System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Position> GetPositionByIds(System.Collections.Generic.List<long> positionIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosition/GetPositionByIds", ReplyAction="http://tempuri.org/IPosition/GetPositionByIdsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Position>> GetPositionByIdsAsync(System.Collections.Generic.List<long> positionIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployee/AddEmployee", ReplyAction="http://tempuri.org/IEmployee/AddEmployeeResponse")]
        LaPerLa.Web.LaPerLaService.Employee AddEmployee(LaPerLa.Web.LaPerLaService.Employee info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployee/AddEmployee", ReplyAction="http://tempuri.org/IEmployee/AddEmployeeResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Employee> AddEmployeeAsync(LaPerLa.Web.LaPerLaService.Employee info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployee/GetEmployeesByShopId", ReplyAction="http://tempuri.org/IEmployee/GetEmployeesByShopIdResponse")]
        System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Employee> GetEmployeesByShopId(long shopId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployee/GetEmployeesByShopId", ReplyAction="http://tempuri.org/IEmployee/GetEmployeesByShopIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Employee>> GetEmployeesByShopIdAsync(long shopId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSale/AddEmployeeSale", ReplyAction="http://tempuri.org/IEmployeeSale/AddEmployeeSaleResponse")]
        LaPerLa.Web.LaPerLaService.EmployeeSale AddEmployeeSale(LaPerLa.Web.LaPerLaService.EmployeeSale info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSale/AddEmployeeSale", ReplyAction="http://tempuri.org/IEmployeeSale/AddEmployeeSaleResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.EmployeeSale> AddEmployeeSaleAsync(LaPerLa.Web.LaPerLaService.EmployeeSale info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSale/GetEmployeeSalesByEmployeeIds", ReplyAction="http://tempuri.org/IEmployeeSale/GetEmployeeSalesByEmployeeIdsResponse")]
        System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.EmployeeSale> GetEmployeeSalesByEmployeeIds(System.Collections.Generic.List<long> employeeIds, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSale/GetEmployeeSalesByEmployeeIds", ReplyAction="http://tempuri.org/IEmployeeSale/GetEmployeeSalesByEmployeeIdsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.EmployeeSale>> GetEmployeeSalesByEmployeeIdsAsync(System.Collections.Generic.List<long> employeeIds, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSale/AddEmployeeTypeSale", ReplyAction="http://tempuri.org/IEmployeeSale/AddEmployeeTypeSaleResponse")]
        LaPerLa.Web.LaPerLaService.EmployeeTypeSale AddEmployeeTypeSale(LaPerLa.Web.LaPerLaService.EmployeeTypeSale info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeSale/AddEmployeeTypeSale", ReplyAction="http://tempuri.org/IEmployeeSale/AddEmployeeTypeSaleResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.EmployeeTypeSale> AddEmployeeTypeSaleAsync(LaPerLa.Web.LaPerLaService.EmployeeTypeSale info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddShop", ReplyAction="http://tempuri.org/IShop/AddShopResponse")]
        LaPerLa.Web.LaPerLaService.Shop AddShop(LaPerLa.Web.LaPerLaService.Shop info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddShop", ReplyAction="http://tempuri.org/IShop/AddShopResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Shop> AddShopAsync(LaPerLa.Web.LaPerLaService.Shop info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetShopsByDistrictId", ReplyAction="http://tempuri.org/IShop/GetShopsByDistrictIdResponse")]
        System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop> GetShopsByDistrictId(long districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetShopsByDistrictId", ReplyAction="http://tempuri.org/IShop/GetShopsByDistrictIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop>> GetShopsByDistrictIdAsync(long districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/CaculateBonus", ReplyAction="http://tempuri.org/IShop/CaculateBonusResponse")]
        LaPerLa.Web.LaPerLaService.Bonus CaculateBonus(long districtId, long shopId, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/CaculateBonus", ReplyAction="http://tempuri.org/IShop/CaculateBonusResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Bonus> CaculateBonusAsync(long districtId, long shopId, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/NewShopCopy", ReplyAction="http://tempuri.org/IShop/NewShopCopyResponse")]
        long NewShopCopy(long shopId, LaPerLa.Web.LaPerLaService.Shop info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/NewShopCopy", ReplyAction="http://tempuri.org/IShop/NewShopCopyResponse")]
        System.Threading.Tasks.Task<long> NewShopCopyAsync(long shopId, LaPerLa.Web.LaPerLaService.Shop info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetAllShops", ReplyAction="http://tempuri.org/IShop/GetAllShopsResponse")]
        System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop> GetAllShops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetAllShops", ReplyAction="http://tempuri.org/IShop/GetAllShopsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop>> GetAllShopsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        string Login(LaPerLa.Web.LaPerLaService.User info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(LaPerLa.Web.LaPerLaService.User info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Logout", ReplyAction="http://tempuri.org/IUser/LogoutResponse")]
        void Logout(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Logout", ReplyAction="http://tempuri.org/IUser/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRule/AddRule", ReplyAction="http://tempuri.org/IRule/AddRuleResponse")]
        LaPerLa.Web.LaPerLaService.Rule AddRule(LaPerLa.Web.LaPerLaService.Rule info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRule/AddRule", ReplyAction="http://tempuri.org/IRule/AddRuleResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Rule> AddRuleAsync(LaPerLa.Web.LaPerLaService.Rule info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRule/GetRulesByShopId", ReplyAction="http://tempuri.org/IRule/GetRulesByShopIdResponse")]
        System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Rule> GetRulesByShopId(long shopId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRule/GetRulesByShopId", ReplyAction="http://tempuri.org/IRule/GetRulesByShopIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Rule>> GetRulesByShopIdAsync(long shopId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopSale/AddShopSale", ReplyAction="http://tempuri.org/IShopSale/AddShopSaleResponse")]
        LaPerLa.Web.LaPerLaService.ShopSale AddShopSale(LaPerLa.Web.LaPerLaService.ShopSale info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopSale/AddShopSale", ReplyAction="http://tempuri.org/IShopSale/AddShopSaleResponse")]
        System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.ShopSale> AddShopSaleAsync(LaPerLa.Web.LaPerLaService.ShopSale info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopSale/GetCurrentMonthShopSale", ReplyAction="http://tempuri.org/IShopSale/GetCurrentMonthShopSaleResponse")]
        System.Collections.Generic.Dictionary<long, System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.ShopSale>> GetCurrentMonthShopSale(System.Collections.Generic.List<long> shopIds, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopSale/GetCurrentMonthShopSale", ReplyAction="http://tempuri.org/IShopSale/GetCurrentMonthShopSaleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<long, System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.ShopSale>>> GetCurrentMonthShopSaleAsync(System.Collections.Generic.List<long> shopIds, string month);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : LaPerLa.Web.LaPerLaService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<LaPerLa.Web.LaPerLaService.IService>, LaPerLa.Web.LaPerLaService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LaPerLa.Web.LaPerLaService.District AddDisctrict(LaPerLa.Web.LaPerLaService.District info) {
            return base.Channel.AddDisctrict(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.District> AddDisctrictAsync(LaPerLa.Web.LaPerLaService.District info) {
            return base.Channel.AddDisctrictAsync(info);
        }
        
        public System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.District> QueryAllDistricts() {
            return base.Channel.QueryAllDistricts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.District>> QueryAllDistrictsAsync() {
            return base.Channel.QueryAllDistrictsAsync();
        }
        
        public LaPerLa.Web.LaPerLaService.District GetDistrictById(long districtId) {
            return base.Channel.GetDistrictById(districtId);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.District> GetDistrictByIdAsync(long districtId) {
            return base.Channel.GetDistrictByIdAsync(districtId);
        }
        
        public LaPerLa.Web.LaPerLaService.Position AddPosition(LaPerLa.Web.LaPerLaService.Position info) {
            return base.Channel.AddPosition(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Position> AddPositionAsync(LaPerLa.Web.LaPerLaService.Position info) {
            return base.Channel.AddPositionAsync(info);
        }
        
        public System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Position> GetPositionByIds(System.Collections.Generic.List<long> positionIds) {
            return base.Channel.GetPositionByIds(positionIds);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Position>> GetPositionByIdsAsync(System.Collections.Generic.List<long> positionIds) {
            return base.Channel.GetPositionByIdsAsync(positionIds);
        }
        
        public LaPerLa.Web.LaPerLaService.Employee AddEmployee(LaPerLa.Web.LaPerLaService.Employee info) {
            return base.Channel.AddEmployee(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Employee> AddEmployeeAsync(LaPerLa.Web.LaPerLaService.Employee info) {
            return base.Channel.AddEmployeeAsync(info);
        }
        
        public System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Employee> GetEmployeesByShopId(long shopId) {
            return base.Channel.GetEmployeesByShopId(shopId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Employee>> GetEmployeesByShopIdAsync(long shopId) {
            return base.Channel.GetEmployeesByShopIdAsync(shopId);
        }
        
        public LaPerLa.Web.LaPerLaService.EmployeeSale AddEmployeeSale(LaPerLa.Web.LaPerLaService.EmployeeSale info) {
            return base.Channel.AddEmployeeSale(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.EmployeeSale> AddEmployeeSaleAsync(LaPerLa.Web.LaPerLaService.EmployeeSale info) {
            return base.Channel.AddEmployeeSaleAsync(info);
        }
        
        public System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.EmployeeSale> GetEmployeeSalesByEmployeeIds(System.Collections.Generic.List<long> employeeIds, string month) {
            return base.Channel.GetEmployeeSalesByEmployeeIds(employeeIds, month);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.EmployeeSale>> GetEmployeeSalesByEmployeeIdsAsync(System.Collections.Generic.List<long> employeeIds, string month) {
            return base.Channel.GetEmployeeSalesByEmployeeIdsAsync(employeeIds, month);
        }
        
        public LaPerLa.Web.LaPerLaService.EmployeeTypeSale AddEmployeeTypeSale(LaPerLa.Web.LaPerLaService.EmployeeTypeSale info) {
            return base.Channel.AddEmployeeTypeSale(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.EmployeeTypeSale> AddEmployeeTypeSaleAsync(LaPerLa.Web.LaPerLaService.EmployeeTypeSale info) {
            return base.Channel.AddEmployeeTypeSaleAsync(info);
        }
        
        public LaPerLa.Web.LaPerLaService.Shop AddShop(LaPerLa.Web.LaPerLaService.Shop info) {
            return base.Channel.AddShop(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Shop> AddShopAsync(LaPerLa.Web.LaPerLaService.Shop info) {
            return base.Channel.AddShopAsync(info);
        }
        
        public System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop> GetShopsByDistrictId(long districtId) {
            return base.Channel.GetShopsByDistrictId(districtId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop>> GetShopsByDistrictIdAsync(long districtId) {
            return base.Channel.GetShopsByDistrictIdAsync(districtId);
        }
        
        public LaPerLa.Web.LaPerLaService.Bonus CaculateBonus(long districtId, long shopId, string month) {
            return base.Channel.CaculateBonus(districtId, shopId, month);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Bonus> CaculateBonusAsync(long districtId, long shopId, string month) {
            return base.Channel.CaculateBonusAsync(districtId, shopId, month);
        }
        
        public long NewShopCopy(long shopId, LaPerLa.Web.LaPerLaService.Shop info) {
            return base.Channel.NewShopCopy(shopId, info);
        }
        
        public System.Threading.Tasks.Task<long> NewShopCopyAsync(long shopId, LaPerLa.Web.LaPerLaService.Shop info) {
            return base.Channel.NewShopCopyAsync(shopId, info);
        }
        
        public System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop> GetAllShops() {
            return base.Channel.GetAllShops();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Shop>> GetAllShopsAsync() {
            return base.Channel.GetAllShopsAsync();
        }
        
        public string Login(LaPerLa.Web.LaPerLaService.User info) {
            return base.Channel.Login(info);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(LaPerLa.Web.LaPerLaService.User info) {
            return base.Channel.LoginAsync(info);
        }
        
        public void Logout(long userId) {
            base.Channel.Logout(userId);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(long userId) {
            return base.Channel.LogoutAsync(userId);
        }
        
        public LaPerLa.Web.LaPerLaService.Rule AddRule(LaPerLa.Web.LaPerLaService.Rule info) {
            return base.Channel.AddRule(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.Rule> AddRuleAsync(LaPerLa.Web.LaPerLaService.Rule info) {
            return base.Channel.AddRuleAsync(info);
        }
        
        public System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Rule> GetRulesByShopId(long shopId) {
            return base.Channel.GetRulesByShopId(shopId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.Rule>> GetRulesByShopIdAsync(long shopId) {
            return base.Channel.GetRulesByShopIdAsync(shopId);
        }
        
        public LaPerLa.Web.LaPerLaService.ShopSale AddShopSale(LaPerLa.Web.LaPerLaService.ShopSale info) {
            return base.Channel.AddShopSale(info);
        }
        
        public System.Threading.Tasks.Task<LaPerLa.Web.LaPerLaService.ShopSale> AddShopSaleAsync(LaPerLa.Web.LaPerLaService.ShopSale info) {
            return base.Channel.AddShopSaleAsync(info);
        }
        
        public System.Collections.Generic.Dictionary<long, System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.ShopSale>> GetCurrentMonthShopSale(System.Collections.Generic.List<long> shopIds, string month) {
            return base.Channel.GetCurrentMonthShopSale(shopIds, month);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<long, System.Collections.Generic.List<LaPerLa.Web.LaPerLaService.ShopSale>>> GetCurrentMonthShopSaleAsync(System.Collections.Generic.List<long> shopIds, string month) {
            return base.Channel.GetCurrentMonthShopSaleAsync(shopIds, month);
        }
    }
}
